Repository GSG-G13/Trakio-api, pull requests merged in 2023-07, with the labels that each got.

#122 Imporving get tasks by project query
  src/database/query/tasks.ts
Labels: awaiting-review

#120 Add delete account query and controller
  src/controllers/auth.ts
  src/controllers/index.ts
  src/database/config/connection.ts
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/user.ts
  src/routers/auth.ts
Labels: approved

#124 Get user data controller
  src/controllers/auth.ts
  src/controllers/index.ts
  src/routers/auth.ts
Labels: awaiting-review

#129 fix: fixing a bug in get task
  src/database/query/tasks.ts
Labels: awaiting-review

#130 Add members to project
  .eslintrc.json
  src/controllers/index.ts
  src/controllers/members.ts
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/members.ts
  src/routers/members.ts
Labels: awaiting-review

#133 132 get all users
  src/controllers/auth.ts
  src/controllers/index.ts
  src/database/query/index.ts
  src/database/query/user.ts
  src/routers/auth.ts
Labels: awaiting-review

#134 Update get users
  src/controllers/auth.ts
  src/database/query/user.ts
  src/routers/auth.ts
Labels: done

#136 Fixing a bug
  src/database/query/user.ts
Labels: done

#138 Create get priorities
  src/controllers/index.ts
  src/controllers/priority.ts
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/priority.ts
  src/routers/index.ts
  src/routers/priority.ts
Labels: approved

#140 Improving the functionality of attachment feature
  src/controllers/attachment.ts
  src/database/config/build.sql
  src/database/query/attachment.ts
  src/helpers/validation/attachmentSchema.ts
  src/interfaces/attachment.ts
Labels: awaiting-review

#128 Create query to edit section in task
  src/database/query/tasks.ts
Labels: approved

#142 Create update project
  src/controllers/index.ts
  src/controllers/project.ts
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/projects.ts
  src/routers/project.ts
Labels: approved

#145 Fixing a bug in update task qury
  src/database/query/tasks.ts
Labels: awaiting-review, done

#151 Deploy settings
  package.json
  src/app.ts
  src/controllers/auth.ts
  src/database/config/connection.ts
  src/interfaces/tokenRequest.ts
Labels: approved

#150 OAuth
  package-lock.json
  package.json
  src/app.ts
  src/controllers/googleOAuth.ts
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/user.ts
Labels: approved
