Repository GSG-G13/Trakio-api, pull requests merged in 2023-06, with the labels that each got.

#3 Create file structure
  .eslintrc.json
  .gitignore
  README.md
  __test__/index.ts
  commitlint.config.js
  example.env
  package-lock.json
  package.json
  src/app.ts
  src/config/index.ts
  src/controllers/index.ts
  src/database/config/build.sql
  src/database/config/connection.ts
  src/database/index.ts
  src/database/query/index.ts
  src/helper/index.ts
  src/index.ts
  src/middleware/index.ts
  src/routes/index.ts
  src/validation/index.ts
  tsconfig.json
Labels: approved

#6 Create Database Schema
  src/database/config/build.sql
  src/database/config/fakeData.sql
Labels: approved

#8 Configure jest with typescript
  __tests__/index.ts
  jest.config.js
Labels: approved

#12 Create verify and sign promises
  example.env
  package-lock.json
  package.json
  src/helper/index.ts
  src/helper/jwtPromises.ts
Labels: awaiting-review

#13 Create validation schemas
  src/validation/index.ts
  src/validation/schema.ts
Labels: awaiting-review

#18 Finish logout
  src/controllers/auth.ts
  src/controllers/index.ts
Labels: awaiting-review

#19 Add db connection
  package-lock.json
  package.json
  src/database/.DS_Store
  src/database/config/connection.ts
Labels: awaiting-review

#16 Adding checkAuth and Custom Error
  .eslintrc.json
  src/helper/customError/customError.ts
  src/helper/index.ts
  src/interfaces/index.ts
  src/interfaces/tokenRequest.ts
  src/interfaces/userData.ts
  src/middleware/checkAuth.ts
Labels: approved

#22 Add check email exist query
  example.env
  package.json
  src/database/config/connection.ts
  src/database/query/user.ts
  src/interfaces/query.ts
Labels: approved

#25 Add user credential function
  src/database/config/index.ts
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/user.ts
  src/interfaces/index.ts
Labels: approved

#28 Login controller
  package-lock.json
  package.json
  src/app.ts
  src/controllers/auth.ts
  src/controllers/index.ts
  src/database/query/index.ts
  src/database/query/user.ts
  src/interfaces/index.ts
  src/interfaces/tokenRequest.ts
  src/interfaces/userData.ts
  src/middleware/checkAuth.ts
  src/routes/auth.ts
  src/routes/index.ts
  src/validation/schema.ts
  tsconfig.json
Labels: approved

#27 Add signup Query
  src/controllers/index.ts
  src/controllers/signup.ts
  src/database/query/user.ts
  src/routes/auth.ts
Labels: approved

#34 Create add task query
  .eslintrc.json
  src/database/config/build.sql
  src/database/query/tasks.ts
  src/helper/jwtPromises.ts
Labels: awaiting-review

#36 Add delete project by id query
  src/controllers/project.ts
  src/database/query/projects.ts
Labels: approved

#49 Create delete task by taskId query
  src/database/query/index.ts
  src/database/query/tasks.ts
Labels: awaiting-review

#42 Create server error
  commitlint.config.js~
  src/database/config/index.ts
  src/interfaces/index.ts
  src/interfaces/joiInterface.ts
  src/middleware/index.ts
  src/middleware/serverError.ts
  src/routers/index.ts
  src/routers/project.ts
Labels: approved

#40 Fixing a promise bug in signUp controller
  src/controllers/auth.ts
Labels: approved

#45 Add get user task query
  src/database/query/tasks.ts
Labels: awaiting-review

#52 Create get project by projectId query
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/projects.ts
Labels: approved

#57 Add project
  src/controllers/auth.ts
  src/controllers/index.ts
  src/controllers/project.ts
  src/database/config/build.sql
  src/database/index.ts
  src/database/query/index.ts
  src/database/query/projects.ts
  src/database/query/tasks.ts
  src/database/query/user.ts
  src/interfaces/index.ts
  src/interfaces/projectData.ts
  src/routers/auth.ts
  src/routers/project.ts
  src/validation/index.ts
  src/validation/projectSchema.ts
Labels: awaiting-review

#56 Add get user task controller
  src/controllers/task.ts
  src/routers/task.ts
Labels: approved

#54 Create delete task by task_id controller
  src/controllers/index.ts
  src/controllers/task.ts
  src/database/config/connection.ts
  src/routers/task.ts
Labels: approved

#63 Create get sections
  src/database/query/index.ts
  src/database/query/section.ts
Labels: approved

#65 Adding fetch tasks by project and section query
  src/database/query/index.ts
  src/database/query/tasks.ts
Labels: approved

#67 Create get sections controller
  src/controllers/index.ts
  src/controllers/section.ts
  src/routers/index.ts
  src/routers/section.ts
Labels: approved

#69 Add fake data on database
  src/database/config/fakeData.sql
Labels: approved

#70 Creating get tasks by project and section
  src/controllers/index.ts
  src/controllers/task.ts
  src/database/query/index.ts
  src/database/query/tasks.ts
  src/routers/task.ts
Labels: approved

#71 Update task
  src/controllers/index.ts
  src/controllers/task.ts
  src/database/query/index.ts
  src/database/query/tasks.ts
  src/interfaces/index.ts
  src/interfaces/task.ts
  src/routers/task.ts
Labels: approved

#72 Fix problem in fakeData.sql
  src/database/config/fakeData.sql
Labels: awaiting-review

#78 Create add attachments query
  src/database/query/attachment.ts
  src/database/query/index.ts
Labels: approved

#80 Create add attachment controller
  src/controllers/attachment.ts
  src/controllers/index.ts
  src/database/query/attachment.ts
  src/database/query/index.ts
  src/interfaces/attachment.ts
  src/interfaces/index.ts
  src/routers/attachment.ts
  src/routers/index.ts
  src/validation/attachmentSchema.ts
  src/validation/index.ts
Labels: approved

#76 Create get attachment controller
  src/controllers/attachment.ts
  src/controllers/index.ts
  src/routers/attachment.ts
Labels: approved

#82 Creating the get members by project query
  src/database/query/index.ts
  src/database/query/members.ts
Labels: awaiting-review, approved

#84 Create get members by project controller
  src/controllers/index.ts
  src/controllers/members.ts
  src/routers/index.ts
  src/routers/members.ts
Labels: approved

#86 Create the client error middleware function
  src/middleware/clientError.ts
  src/middleware/index.ts
  src/routers/index.ts
Labels: approved

#88 Refactor api code
  .eslintrc.json
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  commitlint.config.js
  commitlint.config.js~
  src/app.ts
  src/controllers/attachment.ts
  src/controllers/auth.ts
  src/controllers/index.ts
  src/controllers/members.ts
  src/controllers/project.ts
  src/controllers/section.ts
  src/controllers/task.ts
  src/database/index.ts
  src/database/query/attachment.ts
  src/database/query/index.ts
  src/database/query/members.ts
  src/database/query/projects.ts
  src/database/query/section.ts
  src/database/query/tasks.ts
  src/database/query/user.ts
  src/helper/index.ts
  src/helpers/customError/index.ts
  src/helpers/index.ts
  src/helpers/jwtPromises.ts
  src/helpers/validation/attachmentSchema.ts
  src/helpers/validation/index.ts
  src/helpers/validation/projectSchema.ts
  src/helpers/validation/schema.ts
  src/middleware/checkAuth.ts
  src/middleware/clientError.ts
  src/middleware/index.ts
  src/middleware/serverError.ts
  src/routers/attachment.ts
  src/routers/auth.ts
  src/routers/members.ts
  src/routers/project.ts
  src/routers/section.ts
  src/routers/task.ts
Labels: approved

#94 feat: add the build.ts file
  src/database/config/build.ts
Labels: approved

#91 Create checkMember and checkManager middleware
  .eslintrc.json
  src/controllers/attachment.ts
  src/controllers/auth.ts
  src/controllers/project.ts
  src/controllers/task.ts
  src/database/query/index.ts
  src/database/query/members.ts
  src/database/query/tasks.ts
  src/helpers/validation/schema.ts
  src/interfaces/index.ts
  src/interfaces/roleRequest.ts
  src/interfaces/task.ts
  src/middleware/checkManager.ts
  src/middleware/checkMember.ts
  src/middleware/index.ts
  src/routers/attachment.ts
  src/routers/members.ts
  src/routers/project.ts
  src/routers/task.ts
Labels: awaiting-review

#100 Fixing a bug in route of adding attachment
  src/controllers/attachment.ts
  src/routers/attachment.ts
Labels: awaiting-review

#105 Adding test for auth
  __tests__/auth.ts
  src/controllers/auth.ts
  src/database/config/build.ts
Labels: awaiting-review

#103 Validate params and queries
  .eslintrc.json
  src/controllers/attachment.ts
  src/controllers/members.ts
  src/controllers/project.ts
  src/controllers/task.ts
Labels: approved

#98 Add test for attachment routes
  __tests__/attachment.test.ts
  src/controllers/auth.ts
Labels: approved

#109 Fixing a bug in task controller addTask function
  src/controllers/auth.ts
  src/controllers/task.ts
  src/database/query/members.ts
Labels: approved

#111 Refactoring the check middleware for member and manager
  src/middleware/checkManager.ts
  src/middleware/checkMember.ts
Labels: approved

#113 Fixing the get all user tasks query
  src/database/query/tasks.ts
Labels: approved

#114 Fixing a bug in get all tasks by user
  src/database/query/tasks.ts
Labels: approved

#115 Improving the query
  src/database/config/fakeData.sql
  src/database/query/tasks.ts
Labels: approved

#117 Install morgan and config cors
  .eslintrc.json
  package-lock.json
  package.json
  src/app.ts
  src/database/config/connection.ts
  src/routers/index.ts
Labels: approved

#118 Modifying the connection.ts file
  package.json
  src/app.ts
  src/database/config/connection.ts
  src/routers/index.ts
Labels: awaiting-review
